In [1]:
print("Notebook is working!")

Notebook is working!

In [2]:
import pandas as pd
import numpy as np

print("Libraries imported successfully!")

Libraries imported successfully!

In [3]:
df = pd.read_csv("dataset/water_potability.csv")

print("Dataset loaded successfully!")

Dataset loaded successfully!

In [4]:
df.head()

,ph,Hardness,Solids,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity,Potability
0,NaN,204.890455,20791.318981,7.300212,368.516441,564.308654,10.379783,86.990970,2.963135,0
1,3.716080,129.422921,18630.057858,6.635246,NaN,592.885359,15.180013,56.329076,4.500656,0
2,8.099124,224.236259,19909.541732,9.275884,NaN,418.606213,16.868637,66.420093,3.055934,0
3,8.316766,214.373394,22018.417441,8.059332,356.886136,363.266516,18.436524,100.341674,4.628771,0
4,9.092223,181.101509,17978.986339,6.546600,310.135738,398.410813,11.558279,31.997993,4.075075,0

In [5]:
df.shape

(3276, 10)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3276 entries, 0 to 3275
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ph               2785 non-null   float64
 1   Hardness         3276 non-null   float64
 2   Solids           3276 non-null   float64
 3   Chloramines      3276 non-null   float64
 4   Sulfate          2495 non-null   float64
 5   Conductivity     3276 non-null   float64
 6   Organic_carbon   3276 non-null   float64
 7   Trihalomethanes  3114 non-null   float64
 8   Turbidity        3276 non-null   float64
 9   Potability       3276 non-null   int64
dtypes: float64(9), int64(1)
memory usage: 256.1 KB

In [7]:
df.isnull().sum()

ph                 491
Hardness             0
Solids               0
Chloramines          0
Sulfate            781
Conductivity         0
Organic_carbon       0
Trihalomethanes    162
Turbidity            0
Potability           0
dtype: int64

In [8]:
df.describe()

,ph,Hardness,Solids,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity,Potability
count,2785.000000,3276.000000,3276.000000,3276.000000,2495.000000,3276.000000,3276.000000,3114.000000,3276.000000,3276.000000
mean,7.080795,196.369496,22014.092526,7.122277,333.775777,426.205111,14.284970,66.396293,3.966786,0.390110
std,1.594320,32.879761,8768.570828,1.583085,41.416840,80.824064,3.308162,16.175008,0.780382,0.487849
min,0.000000,47.432000,320.942611,0.352000,129.000000,181.483754,2.200000,0.738000,1.450000,0.000000
25%,6.093092,176.850538,15666.690297,6.127421,307.699498,365.734414,12.065801,55.844536,3.439711,0.000000
50%,7.036752,196.967627,20927.833607,7.130299,333.073546,421.884968,14.218338,66.622485,3.955028,0.000000
75%,8.062066,216.667456,27332.762127,8.114887,359.950170,481.792304,16.557652,77.337473,4.500320,1.000000
max,14.000000,323.124000,61227.196008,13.127000,481.030642,753.342620,28.300000,124.000000,6.739000,1.000000

In [9]:
df['Potability'].value_counts()

Potability
0    1998
1    1278
Name: count, dtype: int64

In [11]:
for col in ['ph', 'Sulfate', 'Trihalomethanes']:
    df[col] = df[col].fillna(df[col].median())

In [12]:
df.isnull().sum()

ph                 0
Hardness           0
Solids             0
Chloramines        0
Sulfate            0
Conductivity       0
Organic_carbon     0
Trihalomethanes    0
Turbidity          0
Potability         0
dtype: int64

In [13]:
corr = df.corr()

corr['Potability'].sort_values(ascending=False)

Potability         1.000000
Solids             0.033743
Chloramines        0.023779
Trihalomethanes    0.006887
Turbidity          0.001581
ph                -0.003014
Conductivity      -0.008128
Hardness          -0.013837
Sulfate           -0.020476
Organic_carbon    -0.030001
Name: Potability, dtype: float64

In [14]:
df['Potability'].value_counts(normalize=True) * 100

Potability
0    60.989011
1    39.010989
Name: proportion, dtype: float64

In [18]:
df['Potability'].value_counts()

Potability
0    1998
1    1278
Name: count, dtype: int64

In [19]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


X = df.drop("Potability", axis=1)
y = df["Potability"]


X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)


rf = RandomForestClassifier(
    random_state=42
)


rf.fit(X_train, y_train)


y_pred = rf.predict(X_test)


print("Accuracy:", accuracy_score(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Accuracy: 0.6585365853658537

Confusion Matrix:
[[355  45]
 [179  77]]

Classification Report:
              precision    recall  f1-score   support

           0       0.66      0.89      0.76       400
           1       0.63      0.30      0.41       256

    accuracy                           0.66       656
   macro avg       0.65      0.59      0.58       656
weighted avg       0.65      0.66      0.62       656

In [20]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score


rf_balanced = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    class_weight='balanced'
)

rf_balanced.fit(X_train, y_train)

y_pred_balanced = rf_balanced.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred_balanced))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_balanced))

print("\nClassification Report:")
print(classification_report(y_test, y_pred_balanced))

Accuracy: 0.6402439024390244

Confusion Matrix:
[[315  85]
 [151 105]]

Classification Report:
              precision    recall  f1-score   support

           0       0.68      0.79      0.73       400
           1       0.55      0.41      0.47       256

    accuracy                           0.64       656
   macro avg       0.61      0.60      0.60       656
weighted avg       0.63      0.64      0.63       656

In [21]:
rf_tuned = RandomForestClassifier(
    n_estimators=300,
    max_depth=10,
    min_samples_leaf=4,
    min_samples_split=10,
    class_weight='balanced',
    random_state=42
)

rf_tuned.fit(X_train, y_train)

y_pred_tuned = rf_tuned.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred_tuned))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_tuned))

print("\nClassification Report:")
print(classification_report(y_test, y_pred_tuned))

Accuracy: 0.649390243902439

Confusion Matrix:
[[304  96]
 [134 122]]

Classification Report:
              precision    recall  f1-score   support

           0       0.69      0.76      0.73       400
           1       0.56      0.48      0.51       256

    accuracy                           0.65       656
   macro avg       0.63      0.62      0.62       656
weighted avg       0.64      0.65      0.64       656

In [22]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(
    rf_tuned,
    X,
    y,
    cv=5,
    scoring='recall'
)

print("Recall Scores:", scores)
print("Average Recall:", scores.mean())

Recall Scores: [0.40234375 0.4627451  0.45882353 0.38671875 0.46484375]
Average Recall: 0.43509497549019616

In [23]:
feature_importance = pd.DataFrame({
    'Feature': X.columns,
    'Importance': rf_tuned.feature_importances_
})

feature_importance.sort_values(
    by='Importance',
    ascending=False
)

           Feature  Importance
4          Sulfate    0.180170
0               ph    0.164493
1         Hardness    0.130822
3      Chloramines    0.118204
2           Solids    0.107267
5     Conductivity    0.082325
8        Turbidity    0.075575
6   Organic_carbon    0.072514
7  Trihalomethanes    0.068631

In [24]:
from sklearn.metrics import classification_report
import numpy as np

y_prob = rf_tuned.predict_proba(X_test)[:, 1]

y_pred_40 = (y_prob >= 0.40).astype(int)

print(classification_report(y_test, y_pred_40))

              precision    recall  f1-score   support

           0       0.79      0.26      0.39       400
           1       0.44      0.89      0.59       256

    accuracy                           0.51       656
   macro avg       0.61      0.58      0.49       656
weighted avg       0.65      0.51      0.47       656

In [25]:
y_pred_45 = (y_prob >= 0.45).astype(int)

print(classification_report(y_test, y_pred_45))

              precision    recall  f1-score   support

           0       0.71      0.48      0.58       400
           1       0.46      0.70      0.56       256

    accuracy                           0.57       656
   macro avg       0.59      0.59      0.57       656
weighted avg       0.62      0.57      0.57       656

In [26]:
import xgboost
print(xgboost.__version__)

3.2.0

In [28]:
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

xgb_model = XGBClassifier(
    n_estimators=300,
    max_depth=4,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    eval_metric='logloss'
)

xgb_model.fit(X_train, y_train)

y_pred_xgb = xgb_model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred_xgb))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_xgb))

print("\nClassification Report:")
print(classification_report(y_test, y_pred_xgb))

Accuracy: 0.6600609756097561

Confusion Matrix:
[[347  53]
 [170  86]]

Classification Report:
              precision    recall  f1-score   support

           0       0.67      0.87      0.76       400
           1       0.62      0.34      0.44       256

    accuracy                           0.66       656
   macro avg       0.64      0.60      0.60       656
weighted avg       0.65      0.66      0.63       656